const Sdata = [
  {
    id: 1,
    imgsrc: "https://wallpapercave.com/wp/wp5295950.jpg",
    title: "HBO Series",
    sname: "Game Of Thrones",
    link: "http://lordfire.persiangig.com/video/game%20of%20thrones/",
  },
  {
    id: 2,
    imgsrc: "https://wallpapercave.com/wp/wp5770344.jpg",
    title: "A Netflix Original Series",
    sname: "DARK",
    link: "https://www.tvseriesnmovies.com/show/index-of-dark/",
  },
  {
    id: 3,
    imgsrc: "https://wallpapercave.com/wp/wp6258930.jpg",
    title: "HBO Series",
    sname: "The BigBang Theory",
    link: "https://dl3.3rver.org/hex1/Series/The.Big.Bang.Theory/ss",
  },
  {
    id: 4,
    imgsrc: "https://wallpapercave.com/wp/wp5696666.jpg",
    title: "A Netflix Original Series",
    sname: "Stranger Things",
    link: "http://www.emlakizmir.net/subtitles/series/Stranger.Things/?SD",
  },
  {
    id: 5,
    imgsrc: "https://wallpapercave.com/wp/wp5110914.jpg",
    title: "A Netflix Original Series",
    sname: "The OA",
    link: "http://indexof.ir/series/the-oa/?__cf_chl_managed_tk__=74da172c13c247f75787eb77484cf69d1014ea58-1620891873-0-AT1SCv3xiS3zP0bRzEzljG_LAKeb79dBA2dPtpBjRhFXuoFtjY0VTVLq-CD3Wz4Ya1pSk5sMc-JtI6U1q_KIHUnBLGrx2JMgPR1jn0TDIWOKNZwvU_AAN5Nom1bl-EqahAT1OFpCbXYDTV8puS7bCdw2Wu_fTT5bxZagq8x4POhu1kjhynzuuAceobgEwZhIo0SozWkRFqGbvTahdDp-S5LskFQLHyZ_vxGYoXvVpn4Bn5k65KPCn3QTzK7P89dBDIWvScqbfvYGJuNbN75-_5egVAds-3_fSgcF7bIyQE30fLYP2pGFVANCg8ua8l67NWU9-4dFYbiJ2ETYDeOa53FifuqqxmaLrph9PHrDQucAENRhU9-s9_TVmeAGP3yOITD2x9GPcdKSm7902yxuigMXQcEOrOyEMwq4xhMa7F0WgKHM4pxcSlPb7SK75V5M1hFzjKtQp3akG-6SuBerMVrn0Yz-wielSq382TTL39SSCN6RboMKRi26FzPAf1EsrJGNMxO2TkglGLG4BLEhEvkPjdzl7k1kdxyCxAVjDkVRSR9DoKccrhb0Dl63ZltrVvAXpkYICwsZgeXkJZ3HSFM7Swb6HYqoJNtkCKBtZMKj2OGIrqJ50PIMnpGYV1goozCq1eeIz5LphCGLkQM_IDZjwDlr2feGHbaSTcTeS37n4FXUufOKkn2rYIEk34djGIMeua85LfYzZ5afM-OCOns",
  },
  {
    id: 6,
    imgsrc: "https://wallpapercave.com/wp/wp2861580.jpg",
    title: "Warner Brothers",
    sname: "Batman Begins",
    link: "http://dl12.dlb3d.ir/F/Batman%20Begins%202005/",
  },
  {
    id: 7,
    imgsrc: "https://wallpapercave.com/wp/wp4777456.jpg",
    title: "Warner Brothers",
    sname: "The Dark Knight",
    link: "https://www.movieminions.org/movie/index-of-the-dark-knight/",
  },
  {
    id: 8,
    imgsrc: "https://wallpapercave.com/wp/PMGZEmT.jpg",
    title: "Warner Brothers",
    sname: "The Dark Knight Rises",
    link: "https://www.movieminions.org/movie/index-of-the-dark-knight/",
  },
  {
    id: 9,
    imgsrc: "https://wallpapercave.com/wp/wp1817975.jpg",
    title: "Warner Brothers",
    sname: "Interstellar",
    link: "https://www.movieminions.org/movie/?id=157336&title=interstellar",
  },
  {
    id: 10,
    imgsrc: "https://wallpapercave.com/wp/wp5053230.jpg",
    title: "Warner Brothers",
    sname: "TENET",
    link: "https://www.movieminions.org/movie/?id=577922&title=tenet",
  },
  {
    id: 11,
    imgsrc: "https://wallpapercave.com/wp/wp2073458.jpg",
    title: "Columbia Pictures",
    sname: "Shutter Island",
    link: "https://www.movieminions.org/movie/?id=11324&title=shutter-island",
  },
  {
    id: 12,
    imgsrc: "https://wallpapercave.com/wp/TycsOQ6.jpg",
    title: "Warner Brothers",
    sname: "Inception",
    link: "https://www.movieminions.org/movie/?id=27205&title=inception",
  },
];
export default Sdata;
